// Screen 4 (docs/architecture.md Sec. 7): the crossed table (instrument
// pair x sun-angle-gap x method) that substantiates the project's actual
// claim with numbers -- read from GET /metrics/matrix, which is itself
// generated by pipeline/match/build_matrix.py from real matcher runs
// against real geometry-confirmed overlaps, not hand-entered.

const METHOD_LABELS = {
  sift: "SIFT",
  akaze: "AKAZE",
  disk_lightglue: "DISK+LightGlue",
};

function InlierCell({ row }) {
  const hasMatch = row.inliers > 0;
  return (
    <td className={hasMatch ? "cell-hit" : "cell-miss"}>
      <div className="cell-inliers">{row.inliers}</div>
      <div className="cell-detail">{row.raw_matches} raw &middot; {(row.inlier_ratio * 100).toFixed(0)}%</div>
    </td>
  );
}

export default function MetricsDashboard({ matrix, loading, error }) {
  if (loading) {
    return (
      <section className="panel panel-wide">
        <h2>Metrics dashboard</h2>
        <p className="muted">Loading comparison matrix...</p>
      </section>
    );
  }

  if (error) {
    return (
      <section className="panel panel-wide">
        <h2>Metrics dashboard</h2>
        <p className="error">{error}</p>
      </section>
    );
  }

  const rows = matrix?.rows || [];
  const methods = [...new Set(rows.map((r) => r.method))];
  const pairKey = (r) => `${r.product_a}__${r.product_b}`;
  const pairs = [...new Map(rows.map((r) => [pairKey(r), r])).values()]
    .sort((a, b) => (a.incidence_gap_deg ?? 0) - (b.incidence_gap_deg ?? 0));

  return (
    <section className="panel panel-wide">
      <h2>Metrics dashboard</h2>
      <p className="muted small">
        Every geometry-confirmed overlapping pair, crossed with every method. RANSAC inlier count
        per cell; green = found real correspondences, gray = zero. Generated by{" "}
        <code>pipeline/match/build_matrix.py</code> from actual matcher runs.
      </p>

      {rows.length === 0 ? (
        <p className="muted">No matrix data yet.</p>
      ) : (
        <div className="matrix-scroll">
          <table className="matrix-table">
            <thead>
              <tr>
                <th>Pair</th>
                <th>Incidence gap</th>
                {methods.map((m) => (
                  <th key={m}>{METHOD_LABELS[m] || m}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {pairs.map((pair) => (
                <tr key={pairKey(pair)}>
                  <td>
                    <div className="mono small">{pair.instrument_a} vs {pair.instrument_b}</div>
                    <div className="muted small">{pair.product_a}<br />{pair.product_b}</div>
                  </td>
                  <td>{pair.incidence_gap_deg != null ? `${pair.incidence_gap_deg.toFixed(1)}°` : "-"}</td>
                  {methods.map((m) => {
                    const row = rows.find((r) => pairKey(r) === pairKey(pair) && r.method === m);
                    return row ? <InlierCell key={m} row={row} /> : <td key={m}>-</td>;
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <p className="muted small">
        Reading: matching survives up to a ~34&deg; sun-incidence gap with classical SIFT/AKAZE,
        but the zero-shot learned baseline (DISK+LightGlue, pretrained on terrestrial photos, no
        lunar fine-tuning) already fails by 26.9&deg; -- see docs/baseline_results.md for the full
        writeup, including the self-match sanity checks confirming these are real results and not
        a broken pipeline.
      </p>
    </section>
  );
}
